apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleapp-frontend
  template:
    metadata:
      labels:
        app: sampleapp-frontend
    spec:
      containers:
      - name: sampleapp-frontend
        image: imagename:latest
        imagePullPolicy: Always
        env:
          - name: VARIABLENAME
            value: "Variable Value"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
